"""
Django settings for doubanMovie project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from crawlDouban.models import Setting

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '98+=d@rf_t83j=+!l$!@i@(*dy&)6^g=h)wh!2n*!0h0z#7q68'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crawlDouban',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'doubanMovie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'doubanMovie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

from mongoengine import connect
connect('doubanDB2')


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR,'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

cookie = Setting.objects.filter(key=str("Cookie"))
# cookie =cookie.value
#
headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393',
    'Cookie': 'bid=rqDgBMKyH_g; douban-fav-remind=1; ll="118183"; _vwo_uuid_v2=DD7E8A4518B1A4CA771C26A9EA09E336D|bce91a9c5e8e067e47f83f5dc35508f5; ps=y; push_doumail_num=0; push_noty_num=0; douban-profile-remind=1; ct=y; __gads=ID=af8be540a0c107f2:T=1588849015:S=ALNI_MYJ4YNDp2QTydl8NaWupHGfaSnL_g; __utmc=30149280; __utmc=223695111; __utmv=30149280.19197; __utmz=223695111.1589088188.35.18.utmcsr=graph.qq.com|utmccn=(referral)|utmcmd=referral|utmcct=/oauth2.0/show; ap_v=0,6.0; _pk_ref.100001.4cf6=%5B%22%22%2C%22%22%2C1589108165%2C%22https%3A%2F%2Fgraph.qq.com%2Foauth2.0%2Fshow%3Fwhich%3DLogin%26display%3Dpc%26scope%3Dget_user_info%26state%3DrqDgBMKyH_g%252523movie%252523https%25253A%252F%252Fmovie.douban.com%252Fsubject%252F33420285%252F%26redirect_uri%3Dhttps%253A%252F%252Faccounts.douban.com%252Fconnect%252Fqq%252Fcallback%26response_type%3Dcode%26client_id%3D100387276%22%5D; _pk_ses.100001.4cf6=*; __utma=30149280.1764587075.1585115693.1589103269.1589108168.42; __utmz=30149280.1589108168.42.17.utmcsr=movie.douban.com|utmccn=(referral)|utmcmd=referral|utmcct=/subject/30257175/; __utmt=1; __utma=223695111.213308978.1585916608.1589103269.1589108186.37; __utmb=223695111.0.10.1589108186; dbcl2="191977354:YzJVJJHCuxE"; ck=X0PY; __utmb=30149280.4.10.1589108168; _pk_id.100001.4cf6=8e798f80dd54ca91.1585916608.36.1589108427.1589103297.'

    # 'Cookie': cookie[0].value
}